Repository iTowns/itowns, pull requests merged in 2018-12, with the labels that each got.

#948 chore: deprecate Panorama components
  src/Core/Prefab/Panorama/PanoramaLayer.js
  src/Core/Prefab/PanoramaView.js
  src/Source/StaticSource.js
Labels: api, chore

#951 feat(layer): add isXXXLayer properties to layers objects
  src/Core/MainLoop.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/Planar/PlanarLayer.js
  src/Core/View.js
  src/Layer/ColorLayer.js
  src/Layer/ElevationLayer.js
  src/Layer/GeometryLayer.js
  src/Layer/Layer.js
  src/Layer/TiledGeometryLayer.js
Labels: api, design

#957 chore: update all npm packages to last version
  package-lock.json
  package.json
Labels: chore

#967 chore(examples): Simplify example page
  examples/index.html
Labels: chore, ready

#965 feat(fetcher): add the possibility to specify fetcher
  src/Provider/DataSourceProvider.js
  src/Source/Source.js
Labels: api, feature, ready

#960 Best place to layer WFS update state
  src/Process/FeatureProcessing.js
Labels: enhancement

#971 make DataSourceProvider more generic
  src/Layer/Layer.js
Labels: ready

#976 chore: remove unless require
  webpack.config.js
Labels: chore

#977 release 2.6.0
  package-lock.json
  package.json
Labels: chore

#983 fix(example): move elevation options in elevation layer
  examples/cubic_planar.html
Labels: bugfix

#985 fix(example) 3dTile
  examples/3dtiles.html
Labels: bugfix
