Repository iTowns/itowns, pull requests merged in 2018-03, with the labels that each got.

#644 perf(protocols): decrease the count of fetch image/xbil
  src/Core/Prefab/GlobeView.js
  src/Process/LayeredMaterialNodeProcessing.js
  test/globe_test.js
  test/layeredmaterialnodeprocessing_unit_test.js
  test/planar_test.js
Labels: enhancement, ready

#687 refactor(core) remove CacheRessource
  src/Core/Scheduler/Providers/CacheRessource.js
  src/Core/Scheduler/Providers/OGCWebServiceHelper.js
  src/Core/Scheduler/Providers/WFS_Provider.js
  src/Core/TileGeometry.js
Labels: in progress

#696 refactor(parsers): move and rename parsers to a new parser directory
  examples/gpx.html
  src/Core/Scheduler/Providers/3dTiles_Provider.js
  src/Core/Scheduler/Providers/OGCWebServiceHelper.js
  src/Core/Scheduler/Providers/PointCloudProvider.js
  src/Core/Scheduler/Providers/Raster_Provider.js
  src/Core/Scheduler/Providers/WFS_Provider.js
  src/Core/View.js
  src/Main.js
  src/Parser/B3dmParser.js
  src/Parser/BatchTable.js
  src/Parser/GLTFLoader.js
  src/Parser/GeoJsonParser.js
  src/Parser/GpxParser.js
  src/Parser/KmzParser.js
  src/Parser/LegacyGLTFLoader.js
  src/Parser/PntsParser.js
  src/Parser/PotreeBinParser.js
  src/Parser/PotreeCinParser.js
  src/Parser/XbilParser.js
  src/Process/LayeredMaterialNodeProcessing.js
  test/feature2mesh_unit_test.js
  test/featureUtils_unit_test.js
Labels: ready

#713 perf(renderer): stop creating new vector for each feature
  src/Renderer/ThreeExtended/Feature2Texture.js
Labels: ready
