Repository iTowns/itowns, pull requests merged in 2018-11, with the labels that each got.

#895 refactor(debug): OBBHelper object to OBBHelper Class ES6
  utils/debug/OBBHelper.js
  utils/debug/TileDebug.js
Labels: design, enhancement

#896 fix(core): wrong OBB from extent
  src/Renderer/ThreeExtended/OBB.js
Labels: bugfix

#905 Add babel-inline-import-loader in webpack
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement, ready

#904 feat(view): add support for a coordinate when creating a GlobeView
  src/Core/Prefab/GlobeView.js
Labels: feature, ready

#866 material to make projective texture from cameras
  docs/config.json
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/Shader/Chunk/project_pars_vertex.glsl
  src/Renderer/Shader/Chunk/projective_texturing_pars_fragment.glsl
  src/Renderer/Shader/Chunk/projective_texturing_pars_vertex.glsl
  src/Renderer/Shader/Chunk/projective_texturing_vertex.glsl
  src/Renderer/Shader/ProjectiveTextureFS.glsl
  src/Renderer/Shader/ProjectiveTextureVS.glsl
  src/Renderer/Shader/ShaderChunk.js
Labels: enhancement, feature

#924 fix(examples): instantiate sources for index.html example
  index.html
Labels: bugfix, ready

#918 docs: add a simple tutorial on geometry layer
  docs/tutorials/Display-a-geometry-layer.md
  docs/tutorials/images/Display-a-geometry-layer-1.png
  docs/tutorials/images/Display-a-geometry-layer-2.png
  docs/tutorials/images/Display-a-geometry-layer-3.png
  docs/tutorials/images/Display-a-geometry-layer-4.png
  docs/tutorials/list.json
Labels: enhancement, ready

#912 refactor(renderer): LayeredMaterial splitted and simplified
  docs/config.json
  examples/multiglobe.html
  examples/planar.html
  examples/planar_vector.html
  examples/split.html
  src/Core/Picking.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/GlobeView.js
  src/Core/Prefab/Planar/PlanarLayer.js
  src/Core/Prefab/PlanarView.js
  src/Core/TileMesh.js
  src/Core/View.js
  src/Layer/InfoLayer.js
  src/Layer/LayerUpdateStrategy.js
  src/Layer/TiledGeometryLayer.js
  src/Main.js
  src/Parser/convertToTile.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Renderer/ColorLayersOrdering.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/LayeredMaterialConstants.js
  src/Renderer/MaterialLayer.js
  src/Renderer/RenderMode.js
  src/Renderer/RendererConstant.js
  src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl
  src/Renderer/Shader/Chunk/elevation_pars_vertex.glsl
  src/Renderer/Shader/Chunk/elevation_vertex.glsl
  src/Renderer/Shader/Chunk/fog_fragment.glsl
  src/Renderer/Shader/Chunk/fog_pars_fragment.glsl
  src/Renderer/Shader/Chunk/lighting_fragment.glsl
  src/Renderer/Shader/Chunk/lighting_pars_fragment.glsl
  src/Renderer/Shader/Chunk/mode_depth_fragment.glsl
  src/Renderer/Shader/Chunk/mode_id_fragment.glsl
  src/Renderer/Shader/Chunk/mode_pars_fragment.glsl
  src/Renderer/Shader/Chunk/overlay_fragment.glsl
  src/Renderer/Shader/Chunk/overlay_pars_fragment.glsl
  src/Renderer/Shader/Chunk/pitUV.glsl
  src/Renderer/Shader/Chunk/project_pars_vertex.glsl
  src/Renderer/Shader/ShaderChunk.js
  src/Renderer/Shader/TileFS.glsl
  src/Renderer/Shader/TileVS.glsl
  src/utils/DEMUtils.js
  test/examples/bootstrap.js
  test/examples/globe.js
  test/examples/layersColorVisible.js
  test/examples/positionGlobe.js
  test/unit/dataSourceProvider.js
  test/unit/layeredmaterial.js
  test/unit/layeredmaterialnodeprocessing.js
  utils/debug/TileDebug.js
Labels: design, enhancement, ready

#927 fix(examples): fix a bad merge in planar_vector
  examples/planar_vector.html
Labels: bugfix, ready
