Repository iTowns/itowns, pull requests merged in 2019-01, with the labels that each got.

#986 fix: windows install no more backslash
  config/replace.config.js
Labels: bugfix

#987 fix: security vulnerability detected in webpack-dev-server
  package-lock.json
  package.json
Labels: bugfix, chore

#850 fix(core): missed layer to layer.source
  src/Core/Scheduler/Scheduler.js
Labels: ready

#988 chore: upgrade to THREE r100
  package-lock.json
  package.json
Labels: chore, enhancement, ready

#991 test: trap console errors when an example page is loaded
  test/examples/bootstrap.js
Labels: bugfix, ready

#1008 fix(example): Immersive example, update camera projection matrix.
  examples/immersive_paris.html
Labels: bugfix

#1005 fix(core): avoid to access to DOM properties
  src/Controls/PlanarControls.js
Labels: bugfix, enhancement

#1010 fix(3dtiles): region extent is treated as an OBB
  CONTRIBUTORS.md
  src/Process/3dTilesProcessing.js
Labels: bugfix

#1003 fix(core): wrong Z min and max to compute tile's obb
  src/Process/LayeredMaterialNodeProcessing.js
Labels: bugfix, ready

#1009 fix(examples): wrong properties in layers json files
  examples/layers/JSONLayers/Region.json
  examples/layers/JSONLayers/ScanEX.json
Labels: bugfix, ready

#1014 chore(docs): add a README concerning the documentation of itowns
  docs/README.md
Labels: chore, ready

#1016 chore: update and rewrite contents in README and other .md files.
  CODING.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  LICENSE.md
  README.md
Labels: chore, doc, ready
