Repository iTowns/itowns, pull requests merged in 2019-06, with the labels that each got.

#1145 fix(converter): don't allow filling for LINES features
  src/Converter/Feature2Texture.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1146 release v2.11.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1149 chore: update npm packages.
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1148 chore: update THREE to r105.2
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1151 fix(geographic): return the correct center of an extent
  src/Core/Geographic/Coordinates.js
  src/Core/Geographic/Extent.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1153 release v2.11.1
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1152 doc(layer): use Source instead of a list of all sources
  src/Layer/ColorLayer.js
  src/Layer/ElevationLayer.js
  src/Layer/GeometryLayer.js
  src/Layer/TiledGeometryLayer.js
Labels: doc :book:, ready :heavy_check_mark:

#1147 feat(example): add a DragNDrop module in examples/
  docs/config.json
  docs/publish.js
  examples/css/example.css
  examples/drag-n-drop.html
  examples/index.html
  examples/js/DragNDrop.js
  examples/screenshots/drag-n-drop.jpg
Labels: demo :roller_coaster:, ready :heavy_check_mark:

#1155 New features orientedImage
  examples/immersive_paris.html
  examples/orientation_utils.html
  src/Layer/OrientedImageLayer.js
  src/Parser/CameraCalibrationParser.js
  src/Renderer/OrientedImageCamera.js
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/Shader/Chunk/projective_texturing_pars_fragment.glsl
  src/Renderer/Shader/Chunk/projective_texturing_pars_vertex.glsl
  src/Renderer/Shader/Chunk/projective_texturing_vertex.glsl
  src/Renderer/Shader/ProjectiveTextureFS.glsl
  src/Renderer/Shader/ProjectiveTextureVS.glsl
Labels: feature :green_apple:, ready :heavy_check_mark:

#1157 refactor(view): change Views to ES6 syntax
  src/Core/Prefab/GlobeView.js
  src/Core/Prefab/PlanarView.js
  src/Core/View.js
Labels: design :straight_ruler:, enhancement :rocket:, ready :heavy_check_mark:

#1156 test(process): don't use a zero-size extent, it is prone to error
  test/unit/layeredmaterialnodeprocessing.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, test :microscope:

#1159 example(dragndrop): update the legend
  examples/css/example.css
  examples/drag-n-drop.html
Labels: demo :roller_coaster:, ready :heavy_check_mark:

#1161 refactor(view): unify events.
  src/Core/Prefab/GlobeView.js
  src/Core/View.js
Labels: refactor

#1163 fix: FT_RTC have to be a local variable
  src/Parser/B3dmParser.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1164 fix(examples): remove UTIF package and use it from a CDN
  examples/tiff.html
  package-lock.json
  package.json
Labels: bugfix :wrench:, ready :heavy_check_mark:
