Repository iTowns/itowns, pull requests merged in 2019-03, with the labels that each got.

#1047 fix(gpx): waypoint are scaling correctly
  examples/gpx.html
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1049 Release v2.8.0.
  package-lock.json
  package.json
Labels: chore

#1050 chore: upgrade packages after new release 2.8.0
  package-lock.json
  package.json
Labels: chore

#1052 fix(core): wrong default parameter in OBB.setFromExtent
  src/Renderer/OBB.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1054 fix(core): event target change doesn't trigged with little change
  src/Utils/CameraUtils.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1055 fix(chore): prepare 'Three js examples' didn't export all functions.
  config/replace.config.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1060 fix(process): bad calling of window.setTimeout
  src/Process/FeatureProcessing.js
  src/Process/LayeredMaterialNodeProcessing.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1061 fix(example): undefined value to enable realistic atmosphere
  examples/globe_travel.html
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1057 refactor ColorLayers sequence order
  src/Layer/TiledGeometryLayer.js
  src/Process/LayeredMaterialNodeProcessing.js
Labels: enhancement :rocket:, ready :heavy_check_mark:

#1058 chore: update to Three r102.1
  examples/gpx.html
  examples/postprocessing.html
  examples/stereo.html
  package-lock.json
  package.json
  src/Renderer/c3DEngine.js
  utils/debug/Debug.js
Labels: chore :truck:, enhancement :rocket:, ready :heavy_check_mark:

#1062 chore: remove PanoramaView, PanoramaLayer, StaticSource and PanoramaTileBuilder
  docs/config.json
  docs/navigation.json
  examples/index.html
  examples/panorama.html
  examples/screenshots/panorama.jpg
  package-lock.json
  package.json
  src/Core/Prefab/Panorama/PanoramaLayer.js
  src/Core/Prefab/Panorama/PanoramaTileBuilder.js
  src/Core/Prefab/PanoramaView.js
  src/Core/View.js
  src/Main.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Source/StaticSource.js
  test/functional/panorama.js
  test/unit/source.js
  utils/debug/Debug.js
Labels: chore :truck:, ready :heavy_check_mark:

#1064 refacto(three): remove all instanceof THREE.*
  src/Controls/GlobeControls.js
  src/Controls/PlanarControls.js
  src/Core/Geographic/Coordinates.js
  src/Core/View.js
  src/Process/FeatureProcessing.js
  src/Renderer/MaterialLayer.js
  src/Utils/DEMUtils.js
Labels: enhancement :rocket:, ready :heavy_check_mark:

#1066 chore(docs): add generation of each property type in typedef
  docs/tmpl/params.tmpl
  docs/tmpl/typedef.tmpl
  src/Core/Scheduler/Cache.js
Labels: chore :truck:, doc :book:, ready :heavy_check_mark:

#1071 Fix planar controls
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1081 fix(controls): fix ORBIT touch event making North down.
  CONTRIBUTORS.md
  src/Controls/GlobeControls.js
Labels: bugfix :wrench:

#1078 fix(examples): refresh debug gui with correct color status.
  examples/layersColorVisible.html
Labels: bugfix :wrench:, ready :heavy_check_mark:
