Repository iTowns/itowns, pull requests merged in 2019-04, with the labels that each got.

#1088 new release iTowns v2.9.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1090 chore: update THREE to v103
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1092 chore(docs): remove console.log
  docs/tmpl/method.tmpl
Labels: chore :truck:, doc :book:, ready :heavy_check_mark:

#1094 chore(build): swap functional and unit testing in npm run test
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1103 example: add a new one with a multipolygon geojson
  examples/index.html
  examples/multipolygon.html
  examples/screenshots/multipolygon.jpg
Labels: demo :roller_coaster:, ready :heavy_check_mark:

#1098 Use Feature class in vector tile parser.
  examples/globe_vector_tiles.html
  examples/js/FeatureToolTip.js
  src/Converter/Feature2Mesh.js
  src/Converter/Feature2Texture.js
  src/Core/Feature.js
  src/Main.js
  src/Parser/GeoJsonParser.js
  src/Parser/VectorTileParser.js
  src/Utils/FeaturesUtils.js
  test/unit/dataSourceProvider.js
  test/unit/feature.js
Labels: enhancement :rocket:, feature :green_apple:, ready :heavy_check_mark:

#1102 test: add tests for sources
  src/Source/Source.js
  src/Source/TMSSource.js
  src/Source/WMSSource.js
  test/unit/source.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, test :microscope:

#1104 test: add unit test on view
  test/unit/view.js
Labels: chore :truck:, ready :heavy_check_mark:, test :microscope:

#1109 doc(tuto): update geometry layer using sources object instead of configuration
  docs/tutorials/Display-a-geometry-layer.md
Labels: doc :book:, ready :heavy_check_mark:

#1111 chore: fix useless or missing conditions.
  src/Core/Feature.js
  src/Core/Geographic/Extent.js
  src/Layer/LayerUpdateStrategy.js
  src/Provider/3dTilesProvider.js
  src/Provider/DataSourceProvider.js
Labels: chore :truck:, ready :heavy_check_mark:

#1114 refacto(crs): create a CRS module
  docs/config.json
  src/Core/Geographic/Coordinates.js
  src/Core/Geographic/Crs.js
  src/Core/Geographic/Extent.js
  src/Core/TileMesh.js
  src/Main.js
  src/Renderer/OBB.js
  test/unit/crs.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, refactor

#1118 refacto(coord): remove C.EPSG_4326
  src/Core/Geographic/Coordinates.js
  src/Core/Prefab/Globe/Atmosphere.js
  src/Core/Prefab/GlobeView.js
Labels: ready :heavy_check_mark:, refactor

#1117 refacto(ellipsoid): move ellipsoidSizes from Coordinates to Ellipsoid
  src/Controls/GlobeControls.js
  src/Core/Geographic/Coordinates.js
  src/Core/Math/Ellipsoid.js
  src/Core/Prefab/Globe/Atmosphere.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/GlobeView.js
  src/Main.js
  src/Utils/CameraUtils.js
  test/unit/CameraUtils.js
Labels: ready :heavy_check_mark:, refactor

#1120 refacto(extent): remove Float64Array from Extent
  src/Core/Geographic/Extent.js
  test/unit/extent.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, refactor

#1125 doc: add the support of quotes to write code strings in documentation
  docs/README.md
  docs/config.json
  docs/static/styles/itowns.css
  src/Controls/PlanarControls.js
  src/Core/Feature.js
  src/Core/Geographic/Crs.js
  src/Core/Geographic/Extent.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/Planar/PlanarLayer.js
  src/Core/Scheduler/Cache.js
  src/Core/Scheduler/Scheduler.js
  src/Core/View.js
  src/Layer/ColorLayer.js
  src/Layer/ElevationLayer.js
  src/Layer/GeometryLayer.js
  src/Layer/Layer.js
  src/Layer/TiledGeometryLayer.js
  src/Provider/Fetcher.js
  src/Provider/URLBuilder.js
  src/Source/FileSource.js
  src/Source/Source.js
  src/Source/TMSSource.js
  src/Source/WFSSource.js
  src/Source/WMSSource.js
  src/Source/WMTSSource.js
Labels: doc :book:, ready :heavy_check_mark:
