Repository iTowns/itowns, pull requests merged in 2019-07, with the labels that each got.

#1169 release v2.12.0
  package-lock.json
  package.json
Labels: chore :truck:

#1172 chore: update npm packages.
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1123 chore(md): add some testing tips for development
  CODING.md
  package.json
Labels: chore :truck:, doc :book:, ready :heavy_check_mark:

#1186 test(extent): add a test to get center for extrem cases
  test/unit/extent.js
Labels: ready :heavy_check_mark:, test :microscope:

#1187 fix(controls): smart zoom in the right direction
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1189 feat(url): add sub-domains handling in url construction
  src/Provider/URLBuilder.js
  test/unit/provider_url.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1174 feat(layer): add full support to scaling for elevation layers
  examples/js/GUI/GuiTools.js
  examples/layers/JSONLayers/GeoidMNT.json
  examples/planar.html
  examples/tiff.html
  src/Converter/convertToTile.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/TileMesh.js
  src/Layer/ElevationLayer.js
  src/Parser/XbilParser.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/MaterialLayer.js
  src/Renderer/OBB.js
  src/Renderer/Shader/Chunk/elevation_pars_vertex.glsl
Labels: feature :green_apple:, ready :heavy_check_mark:

#1190 new unit tests
  CODING.md
  examples/3dtiles.html
  package-lock.json
  package.json
  src/Controls/GlobeControls.js
  src/Core/Scheduler/CancelledCommandException.js
  src/Layer/TiledGeometryLayer.js
  src/Process/FeatureProcessing.js
  src/Provider/PointCloudProvider.js
  test/unit/3dtilesprocess.js
  test/unit/featureprocess.js
  test/unit/globecontrol.js
  test/unit/globeview.js
  test/unit/mock.js
  test/unit/pointcloud.js
  test/unit/tilemesh.js
  test/unit/view.js
Labels: chore :truck:, ready :heavy_check_mark:, test :microscope:

#1191 release v2.13.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1192 fix(elevation): add a removed line from the elevation shader
  examples/layers/JSONLayers/GeoidMNT.json
  src/Renderer/Shader/Chunk/elevation_pars_vertex.glsl
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1193 release v2.13.1
  package-lock.json
  package.json
Labels: chore :truck:
