Repository iTowns/itowns, pull requests merged in 2019-11, with the labels that each got.

#1256 feature(source): add VectorTileSource.
  docs/config.json
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
  src/Converter/textureConverter.js
  src/Main.js
  src/Provider/DataSourceProvider.js
  src/Source/Source.js
  src/Source/VectorTilesSource.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1257 refactor: rename .coords as .extent when it was an Extent
  examples/js/plugins/TIFFParser.js
  src/Converter/textureConverter.js
  src/Parser/VectorTileParser.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Provider/DataSourceProvider.js
  src/Renderer/MaterialLayer.js
  test/unit/dataSourceProvider.js
  test/unit/vectortiles.js
Labels: ready :heavy_check_mark:, refactor

#1260 release v2.16.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1261 chore: update packages.
  package-lock.json
  package.json
  src/Converter/Feature2Mesh.js
  src/Core/TileGeometry.js
  src/Core/View.js
  src/Parser/PntsParser.js
  src/Parser/PotreeBinParser.js
  src/Parser/PotreeCinParser.js
  src/Provider/PointCloudProvider.js
  utils/debug/OBBHelper.js
Labels: chore :truck:, ready :heavy_check_mark:

#1262 chore: remove unused files.
  src/Core/Math/Point2D.js
  src/Core/Math/Rectangle.js
  src/Core/Math/Sphere.js
Labels: chore :truck:, ready :heavy_check_mark:
