Repository iTowns/itowns, pull requests merged in 2019-12, with the labels that each got.

#1264 refacto(cache): ditch Map() in Cache for simple tree
  src/Core/Prefab/TileBuilder.js
  src/Core/Scheduler/Cache.js
  src/Provider/DataSourceProvider.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, refactor

#1266 refactor(controls): simplify animation and globeControls damping.
  src/Controls/GlobeControls.js
  src/Core/AnimationPlayer.js
  test/unit/globecontrol.js
Labels: ready :heavy_check_mark:, refactor

#1271 chore: update packages.
  config/threeExamples.js
  package-lock.json
  package.json
  src/Parser/B3dmParser.js
  src/Parser/deprecated/LegacyGLTFLoader.js
Labels: chore :truck:, ready :heavy_check_mark:

#1272 chore: add proxy argument to functional tests.
  CODING.md
  test/functional/bootstrap.js
Labels: chore :truck:, ready :heavy_check_mark:

#1274 release v2.17.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:
