Repository iTowns/itowns, pull requests merged in 2019-09, with the labels that each got.

#1212 feat(orientation): improved crs support for rotations
  docs/tmpl/page.tmpl
  src/Layer/OrientedImageLayer.js
  src/Utils/OrientationUtils.js
  test/unit/orientationUtils.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1216 release v2.14.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1217 Up packages
  .eslintrc.js
  examples/.eslintrc.js
  package-lock.json
  package.json
  test/functional/.eslintrc.js
Labels: chore :truck:, ready :heavy_check_mark:

#1221 chore: upgrade vulnerable packages
  package-lock.json
Labels: chore :truck:, ready :heavy_check_mark:

#1220 fix(docs): fix some CSS problems when having a small window
  docs/static/styles/itowns.css
  docs/tmpl/main.tmpl
  examples/css/example.css
Labels: chore :truck:, doc :book:, ready :heavy_check_mark:

#1225 chore(doc): fix missing scrolling on content
  docs/static/styles/itowns.css
Labels: doc :book:, ready :heavy_check_mark:

#1226 fix(style): add circle style support.
  src/Core/Style.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1229 refacto(process): clean up and remove useless FileSource case.
  src/Process/LayeredMaterialNodeProcessing.js
Labels: ready :heavy_check_mark:, refactor

#1228 chore(example): add debug ui in some examples.
  examples/js/GUI/GuiTools.js
  examples/source_file_geojson_raster.html
  examples/source_file_gpx_raster.html
  examples/source_file_kml_raster.html
  examples/source_file_shapefile.html
  examples/source_stream_wfs_3d.html
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
  examples/view_25d_map.html
  examples/view_3d_map.html
  utils/debug/TileDebug.js
Labels: chore :truck:, enhancement :rocket:, ready :heavy_check_mark:

#1218 Fix #1215 (Meridian convergence looks good but seems to be applied in reverse)
  src/Utils/OrientationUtils.js
  test/unit/orientationUtils.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1232 chore(es6): use ES6 type class for c3DEngine
  config/threeExamples.js
  src/Renderer/c3DEngine.js
Labels: chore :truck:, design :straight_ruler:, ready :heavy_check_mark:

#1233 chore(controls): remove deprecated methods in GlobeControls
  src/Controls/GlobeControls.js
Labels: chore :truck:, ready :heavy_check_mark:

#1235 fix(3dtile): avoid to clone overrideMaterials to each each assignment.
  src/Parser/B3dmParser.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1234 fix(layer): undefined projection for planar builder.
  src/Core/Prefab/Planar/PlanarLayer.js
  src/Core/Prefab/Planar/PlanarTileBuilder.js
Labels: bugfix :wrench:, ready :heavy_check_mark:
