Repository iTowns/itowns, pull requests merged in 2019-02, with the labels that each got.

#1021 Release v2.7.1.
  package-lock.json
  package.json
Labels: chore

#1026 chore: update THREE.js to r101.1
  package-lock.json
  package.json
Labels: chore, ready

#1029 chore(test): rename test/examples to test/functional
  CODING.md
  package.json
  test/functional/.eslintrc.js
  test/functional/3dtiles.js
  test/functional/CameraUtils.js
  test/functional/GlobeControls.js
  test/functional/bootstrap.js
  test/functional/collada.js
  test/functional/cubic_planar.js
  test/functional/globe.js
  test/functional/globe_geojson_to3D.js
  test/functional/globe_vector.js
  test/functional/globe_vector_tiles.js
  test/functional/globe_wfs_color.js
  test/functional/globe_wfs_extruded.js
  test/functional/gpx.js
  test/functional/layersColorVisible.js
  test/functional/multiglobe.js
  test/functional/oriented_images.js
  test/functional/orthographic.js
  test/functional/panorama.js
  test/functional/planar.js
  test/functional/planar_vector.js
  test/functional/planar_vector_tiles.js
  test/functional/pointcloud.js
  test/functional/pointcloud_globe.js
  test/functional/positionGlobe.js
  test/functional/postprocessing.js
  test/functional/split.js
  test/functional/stereo.js
  test/functional/wfs.js
Labels: chore, ready

#1031 fix(example): change id building in wfs functional test
  test/functional/wfs.js
Labels: bugfix

#1035 chore: fix 'npm ci' when it prints npm version.
  config/prepare.js
Labels: bugfix, chore

#1038 fix(process): fix and unify calls to window.setTimeOut
  src/Core/AnimationPlayer.js
  src/Process/FeatureProcessing.js
  src/Process/LayeredMaterialNodeProcessing.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1041 fix: security vulnerability in lodash
  package-lock.json
  package.json
Labels: chore, ready :heavy_check_mark:
