Repository iTowns/itowns, pull requests merged in 2019-05, with the labels that each got.

#1133 V2.10.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1135 fix(test): test parse Style.
  test/unit/vectortiles.js
Labels: ready :heavy_check_mark:, test :microscope:

#1134 feat(core): export Feature, FeatureCollection and FeatureGeometry
  src/Core/Feature.js
  src/Main.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1132 chore(view): remove support of passing a source as an object
  src/Core/View.js
Labels: chore :truck:, enhancement :rocket:, ready :heavy_check_mark:

#1137 chore: update npm packages.
  config/replace.config.js
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1138 chore: update THREE to r104.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1141 chore(view): remove createXXXLayer methods
  src/Core/Prefab/GlobeView.js
  src/Core/Prefab/PlanarView.js
  src/Main.js
Labels: chore :truck:, ready :heavy_check_mark:

#1139 feature(3dtile): support rtc center from feature.
  src/Parser/B3dmParser.js
  src/Parser/BatchTableParser.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1143 fix(tooltip): display all properties of a feature
  examples/css/example.css
  examples/globe_vector.html
  examples/js/FeatureToolTip.js
  examples/shapefile.html
Labels: demo :roller_coaster:, enhancement :rocket:, ready :heavy_check_mark:
