Repository iTowns/itowns, pull requests merged in 2019-10, with the labels that each got.

#1236 release v2.15.0
  package-lock.json
  package.json
Labels: chore :truck:

#1237 chore: update packages.
  package-lock.json
  package.json
  src/Converter/Feature2Texture.js
  src/Core/Prefab/Globe/Shaders/CloudsVS.glsl
  src/Core/Prefab/Globe/Shaders/GlowFS.glsl
  src/Core/Prefab/Globe/Shaders/GlowVS.glsl
  src/Core/View.js
  src/Provider/Fetcher.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/Shader/TileFS.glsl
  src/Renderer/Shader/TileVS.glsl
Labels: chore :truck:

#1238 fix(utils): change the CRS of the coordinate in FeatureUtils
  src/Utils/FeaturesUtils.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1239 release v2.15.1
  package-lock.json
  package.json
Labels: chore :truck:

#1242 release v2.15.2
  package-lock.json
  package.json
Labels: chore :truck:

#1243 fix(core): forgotten glsl includes.
  src/Renderer/Shader/PointsVS.glsl
  src/Renderer/Shader/ProjectiveTextureVS.glsl
Labels: bugfix :wrench:

#1244 release v2.15.3
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1253 fix(example): avoid collision camera with the ground.
  examples/pointcloud_3d_map.html
Labels: bugfix :wrench:
