Repository iTowns/itowns, pull requests merged in 2019-08, with the labels that each got.

#1195 chore: update npm packages.
  package-lock.json
  package.json
  src/Controls/GlobeControls.js
  src/Core/System/Capabilities.js
  src/Core/View.js
  src/Renderer/c3DEngine.js
  test/functional/bootstrap.js
  test/unit/3dtilesprocess.js
  test/unit/mock.js
  test/unit/orientedImageCamera.js
  test/unit/pointcloud.js
Labels: chore :truck:, ready :heavy_check_mark:

#1194 fix(example): wrong move atmosphere in multi globe.
  examples/multiglobe.html
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1200 refactor(source): extend WMTSSource from TMSSource.
  src/Core/View.js
  src/Source/TMSSource.js
  src/Source/WMTSSource.js
  test/unit/source.js
Labels: ready :heavy_check_mark:, refactor

#1203 Fix CSS and links in examples
  README.md
  examples/images/itowns_logo.png
  examples/index.html
  examples/js/GUI/LoadingScreen.js
  src/Layer/ElevationLayer.js
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1198 feature(point): option to link OrientedImageMaterial to PointsMaterial.
  src/Process/PointCloudProcessing.js
  src/Renderer/PointsMaterial.js
  src/Renderer/Shader/Chunk/projective_texturing_pars_fragment.glsl
  src/Renderer/Shader/PointsFS.glsl
  src/Renderer/Shader/PointsVS.glsl
  src/Renderer/Shader/ProjectiveTextureFS.glsl
Labels: feature :green_apple:, ready :heavy_check_mark:

#1177 feat(parser): add a plugin to parse OGR VRT and CSV files
  examples/config.json
  examples/js/plugins/CSVnVRTParser.js
  examples/plugins_vrt.html
Labels: demo :roller_coaster:, feature :green_apple:, ready :heavy_check_mark:

#1205 feature(core): support fill pattern image for features to raster.
  examples/images/cross.png
  examples/source_file_geojson_raster.html
  src/Converter/Feature2Texture.js
  src/Core/Style.js
  test/unit/mock.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1204 chore(example): correct the view source link
  examples/index.html
Labels: demo :roller_coaster:, ready :heavy_check_mark:

#1208 feature(3dtile): add callback called when new content is added.
  docs/config.json
  src/Provider/3dTilesProvider.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1209 chore(example): fix some CSS misalignement
  examples/3dtiles_basic.html
  examples/css/example.css
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_raster.html
Labels: chore :truck:, demo :roller_coaster:, ready :heavy_check_mark:

#1210 fix(orientedImage): wrong affectation in projective texture shader.
  src/Renderer/Shader/Chunk/projective_texturing_pars_fragment.glsl
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1211 fix(picking): NaN value when getting the tile under the picking position
  src/Core/Picking.js
Labels: bugfix :wrench:, ready :heavy_check_mark:
