Repository iTowns/itowns, pull requests merged in 2020-09, with the labels that each got.

#1453 release v2.24.2
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1455 fix(label): delete LabelLayer if attached layer is also deleted
  src/Core/View.js
  src/Layer/LabelLayer.js
Labels: bugfix :wrench:

#1388 refacto(controls): reuse picked position
  src/Controls/GlobeControls.js
  src/Utils/CameraUtils.js
Labels: enhancement :rocket:

#1456 refacto(material): mutualize common uniform/define methods
  src/Renderer/CommonMaterial.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/PointsMaterial.js
  src/Renderer/Shader/PointsFS.glsl
  src/Renderer/Shader/PointsVS.glsl
Labels: refactor

#1449 refacto: add an abstract PointCloud system
  docs/config.json
  examples/potree_25d_map.html
  examples/potree_3d_map.html
  src/Core/PointCloudNode.js
  src/Core/PotreeNode.js
  src/Core/Scheduler/Scheduler.js
  src/Layer/PointCloudLayer.js
  src/Layer/PotreeLayer.js
  src/Main.js
  src/Provider/PointCloudProvider.js
  src/Source/PotreeSource.js
  test/unit/potree.js
  test/unit/potreelayerparsing.js
  test/unit/potreelayerprocessing.js
Labels: enhancement :rocket:, refactor

#1457 fix(style): correctly read the sprites from VT
  src/Core/Style.js
Labels: bugfix :wrench:

#1458 fix(example): wrong display minimum zoom parameter in immersive view.
  examples/view_immersive.html
Labels: bugfix :wrench:, demo :roller_coaster:

#1460 release v2.24.3
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1465 fix(style): load patterns correctly
  src/Core/Style.js
Labels: bugfix :wrench:

#1467 fix(test): more robust animation testing.
  test/unit/globecontrol.js
Labels: bugfix :wrench:

#1469 fix(label): separate labels dom in layers
  src/Core/TileMesh.js
  src/Layer/LabelLayer.js
  src/Renderer/Label2DRenderer.js
Labels: bugfix :wrench:

#1470 perf(label): don't loop into render() if there is no LabelLayer visible
  src/Renderer/Label2DRenderer.js
Labels: enhancement :rocket:

#1445 feat(parser): add LAS/LAZ files parser
  docs/config.json
  examples/config.json
  examples/laz_dragndrop.html
  package-lock.json
  package.json
  src/Controls/FirstPersonControls.js
  src/Main.js
  src/Parser/LASParser.js
  test/unit/lasparser.js
Labels: feature :green_apple:

#1472 fix(debug): fix debug gui tools.
  examples/css/example.css
  examples/js/GUI/GuiTools.js
  examples/view_3d_map.html
  package-lock.json
  test/functional/GlobeControls.js
  utils/debug/Debug.js
  utils/debug/OBBHelper.js
  utils/debug/TileDebug.js
  utils/debug/charts/ChartConfig.js
  utils/debug/charts/ThreeStatsChart.js
  utils/debug/charts/TileObjectChart.js
  utils/debug/charts/TileVisibilityChart.js
Labels: bugfix :wrench:, demo :roller_coaster:

#1474 release v2.25.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1482 fix(label): delete event to remove LabelLayer.
  src/Core/View.js
Labels: bugfix :wrench:

#1484 chore: update packages.
  package-lock.json
  package.json
Labels: chore :truck:

#1486 [Puppetter] replace deprecated waitFor method.
  test/hooks_functional.js
Labels: bugfix :wrench:, test :microscope:
