Repository iTowns/itowns, pull requests merged in 2020-03, with the labels that each got.

#1329 fix(examples): color line function returned black color
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_3d.html
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1335 fix(VectorTile): Differentiated style caches with the VectorTileSources.
  src/Parser/VectorTileParser.js
  src/Source/VectorTilesSource.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1337 release v2.19.0
  package-lock.json
  package.json
Labels: chore :truck:, ready :heavy_check_mark:

#1339 feat(style): add Style to CSS methods
  src/Core/Style.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1341 fix(examples): change sseThreshold because geometric error sample was…
  examples/3dtiles_basic.html
  test/unit/3dtileslayerprocess.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1340 fix(example): missing parameters in GUITools creation
  examples/view_immersive.html
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1343 refacto(DEMUtils): change the getElevationValueAt method
  docs/config.json
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_3d.html
  src/Renderer/Camera.js
  src/Utils/CameraUtils.js
  src/Utils/DEMUtils.js
  test/functional/view_25d_map.js
  test/unit/CameraUtils.js
Labels: doc :book:, ready :heavy_check_mark:, refactor

#1345 refacto(style): merge addIconToElement into applyToHTML
  src/Core/Style.js
Labels: ready :heavy_check_mark:, refactor

#1348 refactor(geographic): unify and encapsulate crs.
  src/Core/Geographic/Crs.js
  src/Core/Geographic/Extent.js
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/GlobeView.js
  src/Core/Prefab/Planar/PlanarLayer.js
  src/Provider/URLBuilder.js
  src/Renderer/OBB.js
  test/unit/dataSourceProvider.js
  test/unit/extent.js
  test/unit/layeredmaterialnodeprocessing.js
  test/unit/provider_url.js
  test/unit/source.js
Labels: ready :heavy_check_mark:, refactor

#1350 fix(debug): wrong OBBHelper visibility and transforming.
  utils/debug/OBBHelper.js
  utils/debug/TileDebug.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1351 feat(renderer): emit a (in)visible event for LayeredMaterial
  src/Renderer/LayeredMaterial.js
  utils/debug/TileDebug.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1352 fix(view): check every offset for eventToViewCoords
  src/Core/View.js
  test/unit/globecontrol.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1353 feat(style): add support for complex fields
  src/Core/Style.js
Labels: feature :green_apple:, ready :heavy_check_mark:
