Repository iTowns/itowns, pull requests merged in 2020-06, with the labels that each got.

#1404 examples: enable labels in Vector Tiles examples
  examples/css/noto.css
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
Labels: demo :roller_coaster:

#1402 fix(Cache): wrong key handling when the keys count is inferior at 3.
  src/Core/Scheduler/Cache.js
  src/Core/Style.js
  test/unit/cache.js
Labels: bugfix :wrench:

#1407 release v2.22.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1409 example: add a vector tile example with style drag and drop
  examples/config.json
  examples/vector_tile_dragndrop.html
Labels: demo :roller_coaster:

#1408 fix(layer): hide labels when hiding LabelLayers
  src/Core/TileMesh.js
  src/Core/View.js
  src/Layer/LabelLayer.js
  src/Renderer/Label2DRenderer.js
Labels: bugfix :wrench:

#1414 fix(renderer): set the correct size for labels dom element
  src/Renderer/Label2DRenderer.js
  src/Renderer/c3DEngine.js
Labels: bugfix :wrench:

#1417 fix(parser): MultiPoint from geojson files were not read correctly
  src/Parser/GeoJsonParser.js
  test/data/geojson/points.geojson.json
  test/unit/geojson.js
Labels: bugfix :wrench:

#1418 fix(layer): get correct extent destination for a LabelLayer
  src/Layer/LabelLayer.js
Labels: bugfix :wrench:

#1420 refactor(Provider): remove unnecessary fetchedData source case.
  src/Provider/DataSourceProvider.js
Labels: refactor
