Repository iTowns/itowns, pull requests merged in 2020-07, with the labels that each got.

#1428 Add tileMatrixSetLimits in a example layer.
  examples/layers/JSONLayers/Administrative.json
Labels: demo :roller_coaster:

#1427 refactor(Core): re-write Matrix4#setMatrix3().
  src/Parser/CameraCalibrationParser.js
Labels: refactor

#1429 refactor(Vector Tiles): set style in vector tiles parser.
  src/Parser/VectorTileParser.js
  src/Provider/DataSourceProvider.js
  src/Source/VectorTilesSource.js
  test/unit/vectortiles.js
Labels: refactor

#1430 Release v2.23.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1431 refactor(GeoJsonParser): change filteringExtent parsing option
  src/Layer/Layer.js
  src/Parser/GeoJsonParser.js
  src/Provider/DataSourceProvider.js
  src/Source/Source.js
Labels: refactor

#1433 fix(potree): a typo disabled progressive display everytime
  src/Layer/PotreeLayer.js
Labels: bugfix :wrench:

#1434 feature(Label): text stroke width label supports value superior at 1.0.
  examples/css/example.css
  src/Core/Label.js
  src/Core/Style.js
  test/unit/bootstrap.js
  test/unit/style.js
Labels: feature :green_apple:

#1435 perf: remove some instanceof that can be avoided
  src/Layer/PotreeLayer.js
  src/Layer/TiledGeometryLayer.js
  src/Process/handlerNodeError.js
  test/hooks_functional.js
Labels: enhancement :rocket:

#1227 fix(process): error checking level elevation.
  src/Process/LayeredMaterialNodeProcessing.js
  test/unit/dataSourceProvider.js
Labels: bugfix :wrench:

#1441 refactor(Source): clean handling error.
  src/Source/Source.js
  src/Source/TMSSource.js
  src/Source/WFSSource.js
Labels: refactor

#1440 examples(VectorTile): fix wrong max level source.
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
Labels: bugfix :wrench:

#1446 fix(Webgl): tempory fix webgl error.
  package-lock.json
  package.json
  src/Renderer/c3DEngine.js
Labels: bugfix :wrench:
