Repository iTowns/itowns, pull requests merged in 2020-02, with the labels that each got.

#1312 fix(parser): add an option to parse symbols as circles in VT
  src/Core/Style.js
  src/Parser/VectorTileParser.js
  src/Provider/DataSourceProvider.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1313 release v2.18.0
  package-lock.json
  package.json
Labels: chore :truck:

#1315 fix(examples): bad `this` reference in 3dTilesHelper
  examples/js/3dTilesHelper.js
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1317 fix(example): picking in kml raster example.
  examples/js/plugins/FeatureToolTip.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1320 fix(examples): wrong min and max altitude in 2.5D examples.
  examples/source_stream_wfs_25d.html
  examples/view_25d_map.html
  examples/view_multi_25d.html
  test/functional/source_stream_wfs_25d.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1321 chore(test): move variables declaration in describe()
  CODING.md
  test/unit/3dtiles.js
  test/unit/3dtileslayerprocess.js
  test/unit/CameraUtils.js
  test/unit/camera.js
  test/unit/dataSourceProvider.js
  test/unit/feature.js
  test/unit/feature2mesh.js
  test/unit/featureUtils.js
  test/unit/featureprocess.js
  test/unit/globeview.js
  test/unit/obb.js
  test/unit/pointcloud.js
  test/unit/pointcloudlayerprocessing.js
  test/unit/provider_url.js
  test/unit/scheduler.js
  test/unit/source.js
  test/unit/tilemesh.js
  test/unit/vectortiles.js
  test/unit/view.js
Labels: ready :heavy_check_mark:, test :microscope:

#1326 chore(css): change z-index of some html elements in examples
  examples/css/example.css
Labels: demo :roller_coaster:, ready :heavy_check_mark:

#1325 test: write a proper mock of DOMElement
  test/unit/mock.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, test :microscope:

#1324 doc(style): add default values and proper documentation of Style properties
  src/Core/Style.js
  src/Main.js
  test/unit/vectortiles.js
Labels: doc :book:, enhancement :rocket:, ready :heavy_check_mark:

#1327 test(globecontrol): emitEvent on correct DOMelement
  test/unit/globecontrol.js
Labels: enhancement :rocket:, ready :heavy_check_mark:, test :microscope:
