Repository iTowns/itowns, pull requests merged in 2020-04, with the labels that each got.

#1354 release v2.20.0
  package-lock.json
  package.json
  src/Main.js
Labels: ready :heavy_check_mark:, release :rainbow:

#1356 fix(examples): change tile matrix limit to Ortho Layer.
  examples/layers/JSONLayers/Ortho.json
Labels: chore :truck:

#1357 refactor(convert): handling NaN to minAltitude computing.
  src/Converter/Feature2Mesh.js
  src/Process/FeatureProcessing.js
Labels: refactor

#1358 fix(VectorTileParser): wrong layers filtering by zoom.
  src/Parser/VectorTileParser.js
Labels: bugfix :wrench:

#1361 Move fetching Oriented image metadata from Layer to Source
  examples/view_immersive.html
  src/Layer/OrientedImageLayer.js
  src/Source/OrientedImageSource.js
Labels: refactor

#1367 fix(ElevationLayer): avoid to replace value if noDataValue is undefined.
  src/Layer/ElevationLayer.js
  src/Renderer/MaterialLayer.js
Labels: bugfix :wrench:, doc :book:

#1371 fix(Core): unnecessary testing.
  examples/js/GUI/GuiTools.js
  examples/js/plugins/FeatureToolTip.js
  src/Controls/GlobeControls.js
  src/Controls/PlanarControls.js
  src/Core/Geographic/Extent.js
  src/Layer/LayerUpdateStrategy.js
  test/unit/vectortiles.js
Labels: bugfix :wrench:, refactor

#1374 Add deepscan Check.
  README.md
Labels: chore :truck:

#1376 fix(demutils): interpolate values considering noDataValue
  src/Utils/DEMUtils.js
Labels: bugfix :wrench:

#1380 refactor(parser): remove unnecessary extent to parse vector tile file.
  src/Parser/VectorTileParser.js
Labels: refactor

#1379 refacto(style): make the text outline lighter, and limit it to 1px wide
  src/Core/Style.js
  test/unit/style.js
Labels: refactor

#1378 feat(layer): add `getCurrentMaxZoom` property to InfoLayer
  src/Layer/InfoLayer.js
Labels: feature :green_apple:

#1383 fix(examples): wrong altitude points bus line.
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_3d.html
Labels: bugfix :wrench:, demo :roller_coaster:
