Repository iTowns/itowns, pull requests merged in 2020-10, with the labels that each got.

#1493 release v2.26.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1498 fix(example): broken split rendering div.
  examples/effects_split.html
Labels: bugfix :wrench:, demo :roller_coaster:

#1502 fix(test): temporary disable the LabelLayer in wfs25d example
  examples/source_stream_wfs_25d.html
Labels: bugfix :wrench:, test :microscope:

#1471 feat(point): add an intensity range for point clouds
  src/Layer/PointCloudLayer.js
  src/Parser/LASParser.js
  src/Parser/PotreeBinParser.js
  src/Renderer/PointsMaterial.js
  src/Renderer/Shader/PointsVS.glsl
  test/unit/potreeBinParser.js
  utils/debug/PotreeDebug.js
Labels: feature :green_apple:

#1500 feature(Point): add classification support.
  docs/config.json
  src/Parser/LASParser.js
  src/Parser/PotreeBinParser.js
  src/Renderer/PointsMaterial.js
  src/Renderer/Shader/PointsVS.glsl
Labels: feature :green_apple:

#1507 fix(test): switch latest node version from 15 to 14
  .travis.yml
Labels: bugfix :wrench:, test :microscope:

#1506 fix(source): move default format before calling parent constructor
  src/Source/TMSSource.js
  src/Source/WFSSource.js
  src/Source/WMSSource.js
Labels: bugfix :wrench:

#1513 chore(docs): add horizontal scroll on the doc content to see the full…
  docs/static/styles/itowns.css
Labels: chore :truck:, doc :book:
