Repository iTowns/itowns, pull requests merged in 2020-11, with the labels that each got.

#1518 release v2.27.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1519 refactor(planarControls): refactor planar controls as an ES6 class
  src/Controls/PlanarControls.js
Labels: refactor

#1521 fix(PlanarControls): fix refactoring errors
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1523 chore: update packages.
  package-lock.json
  package.json
Labels: chore :truck:

#1524 fix(PlanarView): fix a refactoring error
  src/Core/Prefab/PlanarView.js
Labels: bugfix :wrench:

#1527 feature(core): expose proj4 defs methods.
  src/Core/Geographic/Crs.js
Labels: feature :green_apple:
