Repository iTowns/itowns, pull requests merged in 2020-12, with the labels that each got.

#1528 release v2.28.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1530 feature(controls): add option enable smart travel in planarControls
  src/Controls/PlanarControls.js
Labels: feature :green_apple:

#1533 fix(PlanarControls): remove breaking change
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1534 fix(test): update a deprecated method call
  test/unit/obb.js
Labels: test :microscope:

#1532 Prepare migrating to webpack 5 and remove babel-polyfill
  package-lock.json
  package.json
  webpack.config.js
Labels: chore :truck:

#1539 fix(workflow): wrong path to build docs link.
  docs/publish.js
Labels: bugfix :wrench:, doc :book:

#1540 workflow: add script to unit tests coverage.
  package.json
Labels: chore :truck:
