Repository iTowns/itowns, pull requests merged in 2020-01, with the labels that each got.

#1276 fix(layer): wrong default value for min and max subdivision level.
  src/Core/Prefab/Globe/GlobeLayer.js
  src/Core/Prefab/Planar/PlanarLayer.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1269 refactor(layer): move LayerUpdateState to class structure
  src/Layer/LayerUpdateState.js
Labels: ready :heavy_check_mark:, refactor

#1285 chore: update packages.
  package-lock.json
  package.json
Labels: chore :truck:

#1287 feat(controls): use a more global div for event listening
  src/Controls/FirstPersonControls.js
  src/Controls/FlyControls.js
  src/Controls/GlobeControls.js
  src/Controls/PlanarControls.js
  src/Controls/StreetControls.js
  src/Core/View.js
  test/functional/GlobeControls.js
  test/unit/mock.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1292 refacto(extent): use global variable in isPointInside
  src/Core/Geographic/Extent.js
Labels: enhancement :rocket:, ready :heavy_check_mark:

#1291 feat(style): add more complete parsing of vector tiles style
  src/Core/Style.js
  test/unit/vectortiles.js
Labels: feature :green_apple:, ready :heavy_check_mark:

#1294 fix(test): change value of visible tiles in planar
  test/functional/view_25d_map.js
Labels: bugfix :wrench:, chore :truck:, ready :heavy_check_mark:

#1293 fix(example): don't apply transformation to the camera
  examples/vector_tile_raster_2d.html
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1290 refactor: remove the Feature reference from FeatureGeometry
  examples/js/plugins/CSVnVRTParser.js
  src/Core/Feature.js
  src/Parser/GeoJsonParser.js
  src/Parser/VectorTileParser.js
  test/unit/feature.js
Labels: bugfix :wrench:, enhancement :rocket:, ready :heavy_check_mark:

#1297 Apply parameter segments
  src/Converter/convertToTile.js
Labels: bugfix :wrench:

#1298 Clean oriented image layer
  src/Layer/OrientedImageLayer.js
Labels: refactor

#1306 fix(example): add the GUITools to the parent of viewerDiv
  examples/css/example.css
  examples/js/GUI/GuiTools.js
Labels: bugfix :wrench:, demo :roller_coaster:, ready :heavy_check_mark:

#1305 fix(feature): return style when filtering features
  examples/js/plugins/FeatureToolTip.js
  src/Utils/FeaturesUtils.js
Labels: bugfix :wrench:, ready :heavy_check_mark:

#1284 fix(core): remove objects of a GeometryLayer from the Scene
  src/Layer/GeometryLayer.js
Labels: bugfix :wrench:, ready :heavy_check_mark:
