Repository iTowns/itowns, pull requests merged in 2020-05, with the labels that each got.

#1382 refacto(core): remove BuilderEllipsoidTile#OBB
  src/Core/Prefab/Globe/BuilderEllipsoidTile.js
  src/Core/Prefab/Planar/PlanarTileBuilder.js
  src/Core/Prefab/TileBuilder.js
  src/Renderer/OBB.js
  test/unit/obb.js
Labels: bugfix :wrench:, refactor

#1364 fix(view): allow only `ColorLayer` to be picked by `pickFeaturesAt`
  examples/js/plugins/FeatureToolTip.js
  src/Core/View.js
Labels: doc :book:, refactor

#1384 release v2.21.0
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1389 fix: sort features by order in VectorTileParser
  src/Parser/VectorTileParser.js
  src/Source/VectorTilesSource.js
Labels: bugfix :wrench:

#1397 fix(planar): use correct mouse position in PlanarControls
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1396 refacto(style): get anchor position values instead of CSS
  src/Core/Style.js
Labels: enhancement :rocket:, refactor

#1395 fix(source): set the Style.minzoom correctly in VectorTilesSource
  src/Core/Style.js
  src/Parser/VectorTileParser.js
  src/Source/VectorTilesSource.js
  test/unit/vectortiles.js
Labels: bugfix :wrench:

#1392 Refactor Cache
  src/Core/MainLoop.js
  src/Core/Prefab/TileBuilder.js
  src/Core/Scheduler/Cache.js
  src/Core/Style.js
  src/Layer/ColorLayer.js
  src/Layer/ElevationLayer.js
  src/Layer/GeometryLayer.js
  src/Layer/Layer.js
  src/Layer/OrientedImageLayer.js
  src/Layer/TiledGeometryLayer.js
  src/Provider/DataSourceProvider.js
  src/Source/OrientedImageSource.js
  src/Source/Source.js
  src/Source/WFSSource.js
  test/unit/cache.js
  test/unit/dataSourceProvider.js
  test/unit/extent.js
  test/unit/obb.js
  test/unit/source.js
  utils/debug/3dTilesDebug.js
  utils/debug/TileDebug.js
Labels: refactor
