Repository iTowns/itowns, pull requests merged in 2021-05, with the labels that each got.

#1647 feature(Coordinates): add applyMatrix4 method.
  src/Core/Geographic/Coordinates.js
Labels: feature :green_apple:

#1648 refactor(Feature): declare constant in file begining.
  src/Core/Feature.js
Labels: refactor

#1649 fix(FeatureToolTip): avoid undefined layer on move.
  examples/js/plugins/FeatureToolTip.js
Labels: bugfix :wrench:

#1651 refactor(ColorLayer): remove useless features in ColorLayer command.
  src/Layer/Layer.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Provider/DataSourceProvider.js
Labels: refactor

#1658 refactor(example): remove unuseless variable.
  examples/misc_camera_animation.html
Labels: refactor

#1660 fix(LayeredMaterialNodeProcessing): prevent errors in layer update when removing layer
  src/Process/LayeredMaterialNodeProcessing.js
  src/Process/handlerNodeError.js
Labels: bugfix :wrench:

#1661 fix(debug): update coordinates event on mouse move
  utils/debug/Debug.js
Labels: bugfix :wrench:

#1664 release v2.33.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1666 chore: update packages.
  package-lock.json
  package.json
  src/Parser/deprecated/LegacyGLTFLoader.js
Labels: chore :truck:
