Repository iTowns/itowns, pull requests merged in 2021-06, with the labels that each got.

#1667 fix(3Dtiles): remove debugger command.
  src/Parser/deprecated/LegacyGLTFLoader.js
Labels: bugfix :wrench:

#1668 doc(README): update integration badge to github action
  README.md
Labels: chore :truck:, doc :book:

#1670 fix(LayeredMaterialNodeProcessing): checks for source cache with the layer crs for command cancellation
  src/Process/LayeredMaterialNodeProcessing.js
Labels: bugfix :wrench:

#1671 examples(geojson-file): refactor example to illustrate two ways of displaying data from a file
  examples/source_file_geojson_raster.html
Labels: demo :roller_coaster:

#1672 fix(FeatureToolTip): fix tooltip legend icon in examples
  examples/js/plugins/FeatureToolTip.js
Labels: bugfix :wrench:, demo :roller_coaster:

#1673 feature(Layer): add FeatureGeometryLayer.
  examples/js/plugins/DragNDrop.js
  examples/js/plugins/FeatureToolTip.js
  examples/source_file_geojson_3d.html
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_3d.html
  examples/view_immersive.html
  src/Layer/FeatureGeometryLayer.js
  src/Main.js
  test/unit/featuregeometrylayer.js
Labels: feature :green_apple:

#1677 doc(FeatureGeometryLayer): add jsdoc to documentation config
  docs/config.json
Labels: doc :book:
