Repository iTowns/itowns, pull requests merged in 2021-03, with the labels that each got.

#1600 Release v2.31.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1605 examples: update irrelevant titles in some examples
  examples/misc_clamp_ground.html
  examples/misc_compare_25d_3d.html
  examples/misc_orthographic_camera.html
Labels: refactor

#1604 fix(PlanarControls): prevent triggering new movement when already moving
  src/Controls/PlanarControls.js
  test/unit/planarControls.js
Labels: enhancement :rocket:

#1601 fix(PlanarControls): fix drag when moving out of view's domElement
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1602 feat(PlanarControls): Dynamique cursor shape modifications
  src/Controls/PlanarControls.js
Labels: enhancement :rocket:

#1608 fix(Extent): forgetting zoom property copy, in Extent.as().
  src/Core/Geographic/Extent.js
Labels: bugfix :wrench:

#1595 Remove Source.extentsInsideLimit
  src/Layer/LabelLayer.js
  src/Layer/TiledGeometryLayer.js
  src/Process/FeatureProcessing.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Source/FileSource.js
  src/Source/Source.js
  src/Source/TMSSource.js
  src/Source/WFSSource.js
  src/Source/WMSSource.js
  test/unit/layeredmaterialnodeprocessing.js
  test/unit/source.js
Labels: refactor

#1606 fix(VectorTileSource): failing to open mapbox url format.
  src/Parser/MapBoxUrlParser.js
  src/Source/VectorTilesSource.js
  test/unit/vectortiles.js
Labels: bugfix :wrench:

#1591 fix(Camera): fix resizing
  src/Renderer/Camera.js
  test/unit/camera.js
Labels: bugfix :wrench:

#1613 fix(extent): forget copy zoom in Extent#transformedCopy.
  src/Core/Geographic/Extent.js
Labels: bugfix :wrench:

#1615 docs(TMSSource): add example in doc
  src/Source/TMSSource.js
Labels: doc :book:

#1614 chore: update packages.
  package-lock.json
  package.json
  src/Renderer/LayeredMaterial.js
  test/unit/dataSourceProvider.js
Labels: chore :truck:
