Repository iTowns/itowns, pull requests merged in 2021-12, with the labels that each got.

#1765 fix(test): fetch local laz files behind proxy.
  test/unit/lasparser.js
Labels: bugfix :wrench:, test :microscope:

#1771 chore: change itowns.github.io deploying
  .github/workflows/integration.yml
Labels: chore :truck:

#1772 chore: deploy itowns and potree bundle.
  .github/workflows/integration.yml
Labels: chore :truck:

#1773 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore :truck:

#1776 example(Potree): fix point cloud url for https request and add
  examples/itowns-potree.html
Labels: demo :roller_coaster:
