Repository iTowns/itowns, pull requests merged in 2021-04, with the labels that each got.

#1619 fix(Label): wrong label div translate.
  src/Core/Label.js
  test/unit/label.js
Labels: bugfix :wrench:

#1622 doc(GeometryLayer): fix example and typo regarding Object3D
  src/Layer/GeometryLayer.js
Labels: doc :book:

#1626 release v2.32.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1632 diffuse color terrain doc
  src/Core/View.js
Labels: doc :book:

#1635 fix(PlanarControls): prevent freezing zoom when clicking while zooming with an orthographic camera
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1641 refactor(Source): avoid to cache raster data in Source.
  src/Source/Source.js
Labels: design :straight_ruler:, enhancement :rocket:, refactor

#1642 Fix LabelLayer visibility
  examples/plugins_vrt.html
  examples/source_file_gpx_raster.html
  examples/source_file_kml_raster.html
  examples/source_file_shapefile.html
  examples/vector_tile_dragndrop.html
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
  src/Core/View.js
  src/Layer/LabelLayer.js
  src/Layer/Layer.js
  test/unit/view.js
Labels: refactor

#1644 fix(Controls): replace deprecated THREE.Quaternion.slerp.
  src/Controls/PlanarControls.js
  src/Controls/StreetControls.js
  src/Utils/CameraUtils.js
Labels: refactor
