Repository iTowns/itowns, pull requests merged in 2021-09, with the labels that each got.

#1711 chore(examples): change geoportail key.
  examples/layers/JSONLayers/Ortho.json
  examples/vector_tile_raster_2d.html
  examples/vector_tile_raster_3d.html
Labels: chore :truck:

#1714 Refacto(Controls): switch wheel management to `StateControl`
  src/Controls/GlobeControls.js
  src/Controls/StateControl.js
  test/unit/globecontrol.js
  test/unit/statecontrol.js
Labels: refactor

#1716 release v2.35.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:
