Repository iTowns/itowns, pull requests merged in 2021-02, with the labels that each got.

#1573 refactor(layer): introduce RasterLayer.
  src/Layer/ColorLayer.js
  src/Layer/ElevationLayer.js
  src/Layer/RasterLayer.js
Labels: enhancement :rocket:, refactor

#1574 fix(Terrain): use exact method to compute min and max elevation node
  src/Core/TileMesh.js
  src/Parser/XbilParser.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Utils/DEMUtils.js
Labels: bugfix :wrench:

#1575 refactor(debug): remove three r124 warning.
  src/Core/Picking.js
  utils/debug/Debug.js
Labels: refactor

#1580 feature(VectorTilesSource): store parsed vector tile style as class property
  src/Source/VectorTilesSource.js
Labels: enhancement :rocket:

#1581 refactor(Layer): Layer constructor parameter needs Source.
  examples/js/plugins/FeatureToolTip.js
  examples/source_stream_wfs_25d.html
  src/Core/Prefab/Globe/Atmosphere.js
  src/Layer/Layer.js
  src/Layer/TiledGeometryLayer.js
  test/unit/dataSourceProvider.js
  test/unit/geometrylayer.js
  test/unit/label.js
  test/unit/layer.js
  utils/debug/3dTilesDebug.js
  utils/debug/TileDebug.js
Labels: refactor

#1582 release v2.30.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1585 chore: update package-lock.json.
  package-lock.json
Labels: chore :truck:

#1571 fix(PlanarControls): fix pan movement
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1588 fix(GlobeLayer): doesn't subdivise the pole tile mesh.
  src/Core/Prefab/Globe/GlobeLayer.js
Labels: bugfix :wrench:

#1594 fix(RasterColorTile): wrong getter name.
  src/Renderer/RasterTile.js
Labels: bugfix :wrench:

#1592 View refactoring
  src/Core/View.js
  test/unit/view.js
Labels: refactor
