Repository iTowns/itowns, pull requests merged in 2021-01, with the labels that each got.

#1547 Update remove-old-artifacts.yml
  .github/workflows/remove-old-artifacts.yml
Labels: chore :truck:

#1548 Update actions checkout to v2
  .github/workflows/integration.yml
Labels: bugfix :wrench:, chore :truck:

#1545 Fixes GlobeControls
  src/Controls/GlobeControls.js
Labels: bugfix :wrench:, feature :green_apple:

#1549 Change comment on workflow remove old artifact
  .github/workflows/remove-old-artifacts.yml
Labels: chore :truck:

#1550 chore: upgrade lock file version to 2.0.
  package-lock.json
Labels: chore :truck:

#1561 release v2.29.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1514 chore(docs): update doc
  docs/config.json
  examples/misc_orthographic_camera.html
  examples/view_2d_map.html
  src/Controls/GlobeControls.js
  src/Core/Prefab/PlanarView.js
  src/Core/View.js
  src/Renderer/Camera.js
  test/unit/planarControls.js
  test/unit/view.js
Labels: doc :book:

#1564 fix(PlanarControls): fix issues related to cameraOrtho feature
  src/Controls/PlanarControls.js
Labels: bugfix :wrench:

#1565 release v2.29.1
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: bugfix :wrench:

#1566 fix(3dTile): don't overload the b3dm material.
  src/Parser/B3dmParser.js
Labels: bugfix :wrench:

#1568 release v2.29.2
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1562 chore: update packages.
  package-lock.json
  package.json
Labels: chore :truck:

#1563 refactor(camera): refactor Camera as an ES6 class
  src/Renderer/Camera.js
Labels: refactor

#1569 refactor(Camera): remove matrixProjectionNeedsUpdate.
  src/Controls/PlanarControls.js
  src/Renderer/Camera.js
Labels: refactor
