Repository iTowns/itowns, pull requests merged in 2021-11, with the labels that each got.

#1738 fix(Extent): fix wrong calculating when apply matrix.
  src/Core/Geographic/Extent.js
Labels: bugfix :wrench:

#1736 fix(VectorTileSource): set style parent with style Layer
  src/Source/VectorTilesSource.js
Labels: bugfix :wrench:

#1735 refactor(examples): add wfs labels in 2.5d examples.
  examples/source_stream_wfs_25d.html
  examples/view_25d_map.html
Labels: enhancement :rocket:, demo :roller_coaster:

#1741 fix(Ellipsoid): wrong geodesic distance.
  src/Core/Math/Ellipsoid.js
  test/unit/ellipsoid.js
Labels: bugfix :wrench:

#1749 examples(3dtiles_basic): update 3dtiles sources url
  examples/3dtiles_basic.html
  test/unit/3dtileslayerprocess.js
Labels: demo :roller_coaster:, test :microscope:

#1722 fix(GlobeControls): fix black screen when zooming outside globe
  src/Controls/GlobeControls.js
Labels: bugfix :wrench:

#1748 doc(Ellipsoid): minor fix on geodesicDistance doc
  src/Core/Math/Ellipsoid.js
Labels: doc :book:

#1750 fix(ColorLayer): fix shader when transparent is true
  src/Renderer/LayeredMaterial.js
  src/Renderer/RasterTile.js
  src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl
Labels: bugfix :wrench:

#1757 fix(View): wrong calculate pick radius with distance/zoom.
  src/Core/View.js
Labels: bugfix :wrench:

#1759 release v2.36.1
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1761 fix(VectorTileSource): error if vector tile layer style is undefined.
  src/Source/VectorTilesSource.js
Labels: bugfix :wrench:

#1760 refactor(Coordinates/Extent): rename dimension and distance methods.
  src/Core/Geographic/Coordinates.js
  src/Core/Geographic/Extent.js
  test/unit/coordinate.js
  test/unit/extent.js
Labels: refactor :factory:

#1762 refactor(examples): replace geoservice keys.
  examples/layers/JSONLayers/Administrative.json
  examples/layers/JSONLayers/Cada.json
  examples/layers/JSONLayers/EtatMajor.json
  examples/layers/JSONLayers/IGN_MNT.json
  examples/layers/JSONLayers/IGN_MNT_HIGHRES.json
  examples/layers/JSONLayers/WORLD_DTM.json
Labels: refactor :factory:

#1752 refacto(Feature): defaults buildExtent parameter to true for 2d structure
  examples/js/plugins/CSVnVRTParser.js
  examples/misc_custom_label.html
  examples/plugins_vrt.html
  examples/source_file_geojson_raster.html
  examples/source_file_shapefile.html
  src/Core/Feature.js
  src/Parser/ShapefileParser.js
  src/Source/FileSource.js
  test/functional/source_file_geojson_raster.js
  test/unit/feature.js
  test/unit/geojson.js
  test/unit/label.js
Labels: enhancement :rocket:

#1764 release v2.36.2
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:
