Repository iTowns/itowns, pull requests merged in 2021-07, with the labels that each got.

#1679 tutorial: minor correction to tutorials
  docs/tutorials/Fundamentals.md
Labels: doc :book:

#1681 feature(TMSSource): add support for specific TileMatrix identifier
  src/Provider/URLBuilder.js
  src/Source/TMSSource.js
  test/unit/provider_url.js
Labels: feature :green_apple:

#1682 fix(Label): fix `Style.text.offset` parameter
  src/Core/Label.js
Labels: bugfix :wrench:

#1683 fix(Label): rounds the projected coordinates of labels
  src/Core/Label.js
  test/unit/label.js
Labels: bugfix :wrench:

#1687 doc(Style): add precision on doc
  src/Core/Style.js
Labels: doc :book:

#1690 fix(example): generate correct URL when sharing EPT example
  examples/entwine_simple_loader.html
Labels: bugfix :wrench:, demo :roller_coaster:

#1686 feature(Style): add support for custom label anchor
  src/Core/Style.js
Labels: enhancement :rocket:, feature :green_apple:

#1684 Feature(Style): add support for custom icon in labels
  examples/source_file_kml_raster.html
  src/Core/Label.js
  src/Core/Style.js
  src/Layer/LabelLayer.js
  test/unit/bootstrap.js
  test/unit/label.js
Labels: enhancement :rocket:, feature :green_apple:

#1692 fix(eventToViewCoord): check if event.offset properties are defined
  src/Core/View.js
Labels: bugfix :wrench:

#1693 fix(Label): fix occlusion between icons and label text
  src/Core/Label.js
Labels: bugfix :wrench:

#1688 feature(Label): add support to pass custom domElements to labels
  examples/config.json
  examples/misc_custom_label.html
  src/Core/Label.js
  src/Core/Style.js
  src/Layer/LabelLayer.js
Labels: feature :green_apple:

#1689 chore: expose 3dtiles process methods.
  docs/config.json
  src/Main.js
  src/Process/3dTilesProcessing.js
Labels: api, chore :truck:, design :straight_ruler:, enhancement :rocket:

#1694 release v2.34.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:
