Repository iTowns/itowns, pull requests merged in 2021-08, with the labels that each got.

#1696 fix(CameraUtils): fix bugs in `CameraUtils`
  src/Utils/CameraUtils.js
Labels: bugfix :wrench:

#1511 examples(camera travel): add an example where user can pick points an…
  examples/config.json
  examples/misc_camera_traveling.html
Labels: demo :roller_coaster:

#1697 fix(c3DEngine): fix error when input renderer.domElement is a canvas
  src/Renderer/c3DEngine.js
  test/unit/bootstrap.js
Labels: bugfix :wrench:

#1699 chore: up npm package
  package-lock.json
  package.json
Labels: chore :truck:

#1700 Use the same wheel event across all browsers
  src/Controls/FirstPersonControls.js
  src/Controls/FlyControls.js
  src/Controls/GlobeControls.js
  src/Controls/PlanarControls.js
  test/functional/GlobeControls.js
  test/unit/globecontrol.js
  test/unit/planarControls.js
Labels: refactor

#1702 fix(Feature2Mesh): addapt indices array type from the size of polygon
  src/Converter/Feature2Mesh.js
Labels: enhancement :rocket:, bugfix :wrench:

#1707 fix(ShapefileParser): prevent ignoring input crs wen given
  src/Parser/ShapefileParser.js
Labels: bugfix :wrench:
