Repository iTowns/itowns, pull requests merged in 2022-05, with the labels that each got.

#1857 fix(Minimap): remove focus on minimap, and focus back on view
  src/Utils/gui/Minimap.js
Labels: bugfix :wrench:

#1858 release v2.38.2
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1849 example digital surface model
  examples/config.json
  examples/layers/JSONLayers/IGN_MNS_HIGHRES.json
  examples/view_3d_mns_map.html
Labels: demo :roller_coaster:
