Repository iTowns/itowns, pull requests merged in 2022-04, with the labels that each got.

#1833 docs(core): Add doc for local execution
  README.md
Labels: doc :book:

#1840 fix(GeoidLayer): transformation error on tileMesh.
  src/Converter/Feature2Mesh.js
  src/Converter/convertToTile.js
  src/Core/TileMesh.js
  src/Layer/GeoidLayer.js
  src/Process/FeatureProcessing.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/OBB.js
  src/Renderer/Shader/Chunk/elevation_pars_vertex.glsl
  src/Renderer/Shader/Chunk/geoid_vertex.glsl
  src/Renderer/Shader/ShaderChunk.js
  src/Renderer/Shader/TileVS.glsl
  test/unit/dataSourceProvider.js
  test/unit/feature2mesh.js
  test/unit/featuregeometrylayer.js
  test/unit/featuregeometrylayererror.js
  test/unit/geoidlayer.js
Labels: bugfix :wrench:

#1842 test(GeoidLayer): remove comment.
  test/unit/geoidlayer.js
Labels: chore :truck:

#1846 release v2.38.1
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:
