Repository iTowns/itowns, pull requests merged in 2022-02, with the labels that each got.

#1789 chore: replace data keys.
  examples/source_stream_wfs_25d.html
  examples/source_stream_wfs_3d.html
  examples/source_stream_wfs_raster.html
  examples/view_immersive.html
  src/Layer/ElevationLayer.js
  test/functional/source_stream_wfs_25d.js
  test/unit/demutils.js
Labels: chore :truck:

#1787 release v2.37.0
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:

#1793 chore: update packages.
  config/threeExamples.js
  package-lock.json
  package.json
  src/Parser/deprecated/LegacyGLTFLoader.js
  src/Provider/Fetcher.js
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/PointsMaterial.js
  src/Renderer/c3DEngine.js
Labels: chore :truck:

#1795 chore(deps): bump deps to fix security vulnerability.
  package-lock.json
Labels: chore :truck:

#1798 fix(parser): GeoJsonParser add legacy identifier to fct readCRS()
  src/Parser/GeoJsonParser.js
Labels: enhancement :rocket:, bugfix :wrench:
