Repository iTowns/itowns, pull requests merged in 2022-09, with the labels that each got.

#1895 chore(integration): update potree repository
  .github/workflows/integration.yml
Labels: bugfix :wrench:, chore :truck:

#1876 feature(debug): add altitude to displayed coordinates.
  utils/debug/Debug.js
Labels: feature :green_apple:

#1885 fix(Scheduler): replace url subdomains alternatives
  src/Core/Scheduler/Scheduler.js
  src/Provider/URLBuilder.js
Labels: bugfix :wrench:
