Repository iTowns/itowns, pull requests merged in 2022-03, with the labels that each got.

#1804 fix(View): fix pickCoordinates undefined parameter
  src/Core/View.js
Labels: bugfix :wrench:

#1807 chore: add support ecma 2022
  .babelrc
  .eslintrc.js
  package-lock.json
  package.json
  src/Core/TileMesh.js
  src/Layer/GeometryLayer.js
  src/Layer/RasterLayer.js
  src/Process/LayeredMaterialNodeProcessing.js
  src/Provider/TileProvider.js
  src/Renderer/Camera.js
  src/Renderer/ColorLayersOrdering.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/OBB.js
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/RenderMode.js
  src/Utils/DEMUtils.js
  test/functional/misc_clamp_ground.js
Labels: chore :truck:, refactor :factory:

#1806 feature(Widgets): add a widget to display a scale
  docs/config.json
  examples/config.json
  examples/css/widgets.css
  examples/js/Scale.js
  examples/mars.html
  examples/misc_orthographic_camera.html
  examples/view_25d_map.html
  examples/view_2d_map.html
  examples/view_3d_map.html
  examples/widgets_scale.html
  utils/gui/Main.js
  utils/gui/Scale.js
Labels: feature :green_apple:

#1799 fix(Feature2Mesh): fix wrong computing of clockwise polygon.
  src/Converter/Feature2Mesh.js
  src/Parser/GeoJsonParser.js
Labels: bugfix :wrench:

#1812 example(Widgets): use minimap widget in view 3D example
  examples/view_3d_map.html
  test/functional/GlobeControls.js
Labels: demo :roller_coaster:

#1814 refactor(MainLoop): use class for MainLoop.
  src/Core/MainLoop.js
  test/unit/view.js
Labels: refactor :factory:

#1820 refacto(label): render only object with labels.
  src/Renderer/c3DEngine.js
Labels: refactor :factory:

#1821 refactor(View): move View properties to private fields.
  src/Core/View.js
Labels: refactor :factory:

#1827 fix(VectorTileParser): clock wise polygon wasn't calculated.
  src/Parser/VectorTileParser.js
Labels: bugfix :wrench:
