Repository iTowns/itowns, pull requests merged in 2023-03, with the labels that each got.

#2022 Update 3D Tiles dataset to textured one
  examples/3dtiles_25d.html
Labels: enhancement :rocket:, demo :roller_coaster:, 3d-tiles

#2031 refactor(TileMesh): new structuring of the data linked to the node.
  src/Core/TileMesh.js
  src/Process/FeatureProcessing.js
  src/Process/ObjectRemovalHelper.js
  utils/debug/TileDebug.js
Labels: refactor :factory:

#2033 refactor(GlobeLayer): pass in static the method horizonCulling.
  src/Core/Prefab/Globe/GlobeLayer.js
Labels: refactor :factory:

#2034 refactor(LayerUpdateState): add hasFinished method.
  src/Layer/LayerUpdateState.js
Labels: refactor :factory:

#2036 refactor(RasterTile): emit event when raster elevation changed.
  src/Layer/ElevationLayer.js
  src/Renderer/RasterTile.js
  test/unit/tilemesh.js
Labels: refactor :factory:

#2035 refactor(TileMesh): add change visibility event.
  src/Core/TileMesh.js
Labels: feature :green_apple:, refactor :factory:

#2039 refactor(Label): optimize elevation update.
  src/Core/Label.js
  src/Layer/LabelLayer.js
Labels: perf :horse_racing:

#2018 feat(view): allow to pass an array of layers for picking
  src/Core/View.js
Labels: enhancement :rocket:

#2055 fix(Parser): detect if original source have elevation data with multi-features
  src/Parser/GeoJsonParser.js
Labels: bug :bug:

#2058 refactor(GlobeView): move sun light, from tileLayer to main scene.
  src/Core/Prefab/GlobeView.js
Labels: refactor :factory:
