Repository iTowns/itowns, pull requests merged in 2024-04, with the labels that each got.

#2314 chore: replace the CDN from unpkg to jsdelivr
  examples/effects_stereo.html
  examples/misc_collada.html
  examples/view_3d_map_webxr.html
  examples/view_multi_25d.html
  src/Parser/LASLoader.js
Labels: chore :truck:

#2313 feat: Remove WebGL1 support
  src/Core/Deprecated/Undeprecator.js
  src/Core/Prefab/Globe/Shaders/CloudsFS.glsl
  src/Core/Prefab/GlobeView.js
  src/Core/Prefab/PlanarView.js
  src/Core/Prefab/TileBuilder.js
  src/Core/Prefab/computeBufferTileGeometry.js
  src/Core/System/Capabilities.js
  src/Core/TileGeometry.js
  src/Core/View.js
  src/Provider/Fetcher.js
  src/Renderer/LayeredMaterial.js
  src/Renderer/OrientedImageMaterial.js
  src/Renderer/PointsMaterial.js
  src/Renderer/Shader/Chunk/WebGL2_pars_fragment.glsl
  src/Renderer/Shader/Chunk/WebGL2_pars_vertex.glsl
  src/Renderer/Shader/Chunk/elevation_pars_vertex.glsl
  src/Renderer/Shader/Chunk/mode_depth_fragment.glsl
  src/Renderer/Shader/Chunk/project_pars_vertex.glsl
  src/Renderer/Shader/PointsFS.glsl
  src/Renderer/Shader/PointsVS.glsl
  src/Renderer/Shader/ProjectiveTextureFS.glsl
  src/Renderer/Shader/ProjectiveTextureVS.glsl
  src/Renderer/Shader/ShaderChunk.js
  src/Renderer/Shader/TileFS.glsl
  src/Renderer/Shader/TileVS.glsl
  src/Renderer/c3DEngine.js
  test/unit/fetcher.js
  test/unit/potree.js
Labels: chore :truck:, refactor :factory:

#2322 release v2.43.1
  changelog.md
  package-lock.json
  package.json
  src/Main.js
Labels: release :rainbow:
