Repository iTowns/itowns, pull requests merged in 2024-07, with the labels that each got.

#2349 fix(test): import HttpsProxyAgent
  test/unit/potree2.js
  test/unit/potree2layerparsing.js
Labels: test :microscope:

#2303 feat: introducing workers for LAS parser
  src/Parser/LASParser.js
  src/Worker/LASLoaderWorker.js
  test/unit/entwine.js
  test/unit/lasparser.js
  webpack.config.cjs
Labels: enhancement :rocket:, architecture :department_store:

#2370 fix(parser): wrong shpjs 6.0.1 using
  src/Parser/ShapefileParser.js
Labels: bug :bug:
